from pathlib import Path
p=Path('varelq/dist/assets/app.js');s=p.read_text(encoding='utf-8')
s=s.replace("['reliability','Agent reliability','◈']];","['reliability','Agent reliability','◈'],['organization','Organization',''],['settings','Settings','']];")
a=s.index('const overview=');b=s.index('function investigations()',a)
s=s[:a]+'''const overview=()=>`${header('Workspace overview','A clear view of your reviews and operational activity.',button('Upload documents','documents',true))}${metrics()}<div class="overview-split">${card(`<div class="section-title"><div><span class="eyebrow">WORK QUEUE</span><h2>Needs your review</h2></div>${badge(successful().filter(r=>r.decision==='pending').length+' pending')}</div>${successful().filter(r=>r.decision==='pending').slice(0,3).map(r=>`<button class="review-row" data-run="${r.id}"><span class="file-mark">${glyph('documents')}</span><span><strong>${esc(r.invoice_reference)}</strong><small>${esc(r.supplier)}</small></span><span class="review-value">${esc(r.invoice_total??'—')} ${esc(r.currency)}<small>View investigation ↗</small></span></button>`).join('')||'<div class="empty-state">You’re all caught up.<small>New investigations will appear here.</small></div>'}`)}${card(`<span class="eyebrow">RELIABILITY</span><h2>Every finding has a source.</h2><p>Review recurring agent failures alongside the conversations and tool results that support them.</p>${button('Open agent reliability →','reliability')}<div class="connection-line"><span class="status-dot ${state.health?.nim_configured?'connected':''}"></span>${state.health?.nim_configured?'NVIDIA connection configured':'NVIDIA connection not configured'}</div>`,'feature-panel')}</div>${card('<div class="section-title"><div><span class="eyebrow">ACTIVITY</span><h2>Recent analyses</h2></div><a class="text-link" href="#agents">View all activity ↗</a></div>'+runList(state.runs.slice(0,6)),'activity-panel')}`;
''' + s[b:]
a=s.index('function render()');b=s.index('async function request(',a)
s=s[:a]+'''const defaults={name:'My organization',industry:'',region:'',operator:'Local operator',email:'',theme:'light',density:'comfortable',motion:'system'};
let preferences;try{preferences={...defaults,...JSON.parse(localStorage.getItem('varelq.preferences')||'{}')}}catch{preferences={...defaults}}
const paths={overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',investigations:'M10 3H5v18h14V8l-5-5h-4 M14 3v5h5 M8 13h8 M8 17h5',documents:'M8 3h8l4 4v14H8z M16 3v5h4 M4 7v13',suppliers:'M4 21V7l8-4 8 4v14 M9 21v-6h6v6 M8 8h1 M15 8h1 M8 11h1 M15 11h1',inventory:'M3 7l9-4 9 4v10l-9 4-9-4z M3 7l9 4 9-4 M12 11v10',agents:'M3 12h4l3-8 4 16 3-8h4',reliability:'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z M8 12l3 3 5-6',organization:'M3 21V9h7v12 M10 21V3h11v18 M6 12h1 M6 16h1 M14 7h3 M14 11h3 M14 15h3',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M4 7l3-3 3 2h4l3-2 3 3-2 3v4l2 3-3 3-3-2h-4l-3 2-3-3 2-3v-4z'};
function glyph(name){return `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.documents}"/></svg>`}
const initials=()=>preferences.name.trim().split(/\\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'V';
const option=(value,label,current)=>`<option value="${value}" ${current===value?'selected':''}>${label}</option>`;
const organization=()=>`${header('Organization','The identity behind your local workspace.')}<div class="settings-layout"><aside class="settings-nav"><a href="#organization" class="selected">Organization profile</a><a href="#settings">Personal preferences</a></aside><div><form id="organization-form" class="card settings-card"><div class="section-title"><div><h2>Organization profile</h2><p>Used in navigation and workspace identification.</p></div><span class="org-avatar large">${esc(initials())}</span></div><div class="form-grid"><label>Organization name<input name="name" required maxlength="80" value="${esc(preferences.name)}" autocomplete="organization"></label><label>Industry<input name="industry" maxlength="80" value="${esc(preferences.industry)}" placeholder="e.g. Manufacturing"></label><label>Country or region<input name="region" maxlength="80" value="${esc(preferences.region)}" placeholder="e.g. Morocco" autocomplete="country-name"></label><label>Your name<input name="operator" required maxlength="80" value="${esc(preferences.operator)}" autocomplete="name"></label><label class="full-width">Contact email <span class="muted">optional</span><input name="email" type="email" maxlength="160" value="${esc(preferences.email)}" placeholder="you@company.com" autocomplete="email"></label></div><footer class="form-footer"><span>Stored in this browser.</span><button class="button primary" type="submit">Save organization</button></footer></form>${card('<h2>Workspace access</h2><div class="member-row"><span class="org-avatar">'+esc(initials())+'</span><div><strong>'+esc(preferences.operator)+'</strong><small>Local operator · this computer</small></div>'+badge('Local access')+'</div><p>This installation has one local workspace. Organization details do not create separate data stores or access controls. Shared workspaces and invitations require an authenticated deployment.</p>','settings-card')}</div></div>`;
const settings=()=>`${header('Settings','Make the workspace feel right for the way you work.')}<div class="settings-layout"><aside class="settings-nav"><a href="#settings" class="selected">Appearance & behavior</a><a href="#organization">Organization profile</a></aside><div><form id="settings-form" class="card settings-card"><h2>Appearance & behavior</h2><div class="setting-row"><div><strong>Color theme</strong><p>A quiet palette for focused work.</p></div><select name="theme" aria-label="Color theme">${option('light','Light',preferences.theme)}${option('dark','Dark',preferences.theme)}${option('system','Use system setting',preferences.theme)}</select></div><div class="setting-row"><div><strong>Display density</strong><p>Control spacing in lists and tables.</p></div><select name="density" aria-label="Display density">${option('comfortable','Comfortable',preferences.density)}${option('compact','Compact',preferences.density)}</select></div><div class="setting-row"><div><strong>Motion</strong><p>Subtle transitions with a reduced-motion option.</p></div><select name="motion" aria-label="Motion">${option('system','Use system setting',preferences.motion)}${option('full','Subtle motion',preferences.motion)}${option('reduced','Reduce motion',preferences.motion)}</select></div><footer class="form-footer"><span>Preferences apply to this browser.</span><button class="button primary" type="submit">Save preferences</button></footer></form>${card(`<div class="section-title"><div><h2>NVIDIA integration</h2><p>Connection managed by the local server.</p></div>${badge(state.health?.nim_configured?'Configured':'Not configured',state.health?.nim_configured?'success':'warning')}</div><div class="setting-row"><span>Model</span><code>${esc(state.health?.model||'Unavailable')}</code></div><p>Your key is never stored in browser preferences. To replace it, restart the launcher and enter the new key at its hidden prompt.</p>${button('Check connection','refresh')}`,'settings-card')}${card('<h2>Data & privacy</h2><p>Analysis results and extracted text are stored on this computer. Selected document text and traces are sent to NVIDIA only when you request analysis.</p><p>Organization information and display preferences stay in this browser.</p>','settings-card')}</div></div>`;
function applyPreferences(){const dark=preferences.theme==='dark'||preferences.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches;document.documentElement.dataset.theme=dark?'dark':'light';document.documentElement.dataset.density=preferences.density;document.documentElement.dataset.motion=preferences.motion==='reduced'||preferences.motion==='system'&&matchMedia('(prefers-reduced-motion: reduce)').matches?'reduced':'full'}
let renderedRoute='';
function render(){applyPreferences();const changed=renderedRoute!==state.route;renderedRoute=state.route;const navLink=([id,label])=>`<a href="#${id}" class="nav-link ${state.route===id?'active':''}" ${state.route===id?'aria-current="page"':''}>${glyph(id)}<span>${label}</span></a>`;document.getElementById('app').innerHTML=`<a class="skip-link" href="#main-content">Skip to content</a><div class="app-shell"><aside class="sidebar" aria-label="Workspace navigation"><a class="brand" href="#overview"><span class="brand-mark">v</span><span>varelq<span class="brand-period">.</span></span></a><a href="#organization" class="workspace"><span class="org-avatar">${esc(initials())}</span><span><strong>${esc(preferences.name)}</strong><small>Local workspace</small></span><span class="workspace-chevron">⌄</span></a><nav aria-label="Main navigation"><div class="nav-label">WORKSPACE</div>${nav.slice(0,2).map(navLink).join('')}<div class="nav-label">RECORDS</div>${nav.slice(2,5).map(navLink).join('')}<div class="nav-label">INTELLIGENCE</div>${[nav[6],nav[5]].map(navLink).join('')}</nav><div class="sidebar-bottom">${nav.slice(7).map(navLink).join('')}<div class="operator"><span class="operator-avatar">${esc((preferences.operator||'L')[0].toUpperCase())}</span><span><strong>${esc(preferences.operator)}</strong><small>Local operator</small></span><span class="status-dot connected"></span></div></div></aside>${state.menu?'<button class="mobile-overlay" data-action="menu" aria-label="Close navigation"></button>':''}<div class="main-shell"><header class="topbar"><div class="breadcrumb"><button class="mobile-menu" data-action="menu" aria-label="Toggle navigation" aria-expanded="${state.menu}">☰</button><span>${esc(preferences.name)}</span><span class="breadcrumb-divider">/</span><strong>${esc(nav.find(n=>n[0]===state.route)?.[1]||'Overview')}</strong></div><a class="connection-status" href="#settings"><span class="status-dot ${state.health?.nim_configured?'connected':''}"></span>${state.health?(state.health.nim_configured?'NVIDIA connected':'Setup required'):'Connecting…'}</a></header><main id="main-content" tabindex="-1" class="${changed?'page-enter':''}">${state.error?`<div class="api-error" role="alert">${esc(state.error)}</div>`:''}${state.notice?`<div class="notice" role="status">${esc(state.notice)}</div>`:''}${state.pending?'<div class="pending-banner" role="status"><span class="loading-indicator"></span>Processing your request<span>Waiting for NVIDIA</span></div>':''}${({overview,investigations,documents,suppliers,inventory,agents,reliability,organization,settings}[state.route]||overview)()}</main><footer class="workspace-footer"><span>VARELQ · Operations workspace</span><span>Evidence before decisions.</span></footer></div></div>`;document.body.classList.toggle('menu-open',state.menu)}
document.addEventListener('submit',e=>{if(!['organization-form','settings-form'].includes(e.target.id))return;e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(data.name!==undefined&&!data.name.trim()){e.target.elements.name.setCustomValidity('Enter an organization name.');e.target.elements.name.reportValidity();return}const updated={...preferences,...Object.fromEntries(Object.entries(data).map(([k,v])=>[k,v.trim()]))};try{localStorage.setItem('varelq.preferences',JSON.stringify(updated));preferences=updated;state.notice=e.target.id==='organization-form'?'Organization details saved.':'Preferences saved.';state.error='';render()}catch{state.error='Your browser could not save preferences. Check browser storage permissions.';render()}});
for(const query of ['(prefers-color-scheme: dark)','(prefers-reduced-motion: reduce)'])matchMedia(query).addEventListener('change',applyPreferences);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.menu){state.menu=false;render()}});
''' +s[b:]
s=s.replace("<div class=\"eyebrow\">VARELQ / LIVE WORKSPACE</div>","<div class=\"eyebrow\">OPERATIONS WORKSPACE</div>")
s=s.replace("<td>${esc(new Date(r.created).toLocaleString())}</td>","<td class=\"date-cell\">${esc(new Date(r.created).toLocaleDateString(undefined,{month:'short',day:'numeric'}))}<small>${esc(new Date(r.created).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'}))}</small></td>")
s=s.replace("<td>${esc(r.invoice_reference||r.source_label||r.kind)}</td>","<td class=\"source-cell\" title=\"${esc(r.invoice_reference||r.source_label||r.kind)}\"><strong>${esc(r.invoice_reference||r.source_label||r.kind)}</strong><small>${r.kind==='documents'?'Document analysis':'Agent reliability'}</small></td>")
s=s.replace("badge(r.status,r.status==='success'?'success':'warning')","badge(r.status==='success'?'Completed':'Failed',r.status==='success'?'success':'warning')")
s=s.replace("<td>${esc(r.decision||'—')}</td>","<td>${esc(({pending:'Pending review',reviewed:'Reviewed',needs_clarification:'Needs clarification'})[r.decision]||'—')}</td>")
s=s.replace("<td>${r.status==='success'?","<td class=\"run-action\">${r.status==='success'?")
s=s.replace("state.route=location.hash.slice(1)||'overview';state.menu=false;render()","state.route=location.hash.slice(1)||'overview';state.menu=false;state.notice='';render()")
s=s.replace("function go(route){state.route=route;state.menu=false;","function go(route){state.route=route;state.menu=false;state.notice='';")
s=s.replace("${state.logs.length} traces loaded. Nothing is analyzed until you click the NVIDIA button.","${state.logs.length} traces loaded. ${x?'Showing the saved analysis below.':'Ready for analysis when you are.'}")
p.write_text(s,encoding='utf-8')
